### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by TheDarknessz0rz** [sqlmapproject/sqlmap#1172]
I've no idea why this is happening.

[00:14:35] [CRITICAL] unhandled exception occurred in sqlmap/1.0-dev-nongit-20150222. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you
sqlmap version: 1.0-dev-nongit-20150222
Python version: 2.7.6
Operating system: posix
Command line: sqlmap.py -u *********************************** --dbs
Technique: QUERY
Back-end DBMS: MySQL (fingerprinted)
Traceback (most recent call last):
  File "sqlmap.py", line 102, in main
    start()
  File "lib/controller/controller.py", line 603, in start
    action()
  File "lib/controller/action.py", line 106, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "plugins/generic/databases.py", line 108, in getDbs
    values = inject.getValue(query, blind=False, time=False)
  File "lib/request/inject.py", line 404, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "lib/techniques/error/use.py", line 289, in errorUse
    count = unArrayizeValue(_oneShotErrorUse(countedExpression, countedExpressionFields))
  File "lib/techniques/error/use.py", line 91, in _oneShotErrorUse
    query = agent.prefixQuery(vector)
  File "lib/core/agent.py", line 206, in prefixQuery
    expression = self.cleanupPayload(expression)
  File "lib/core/agent.py", line 281, in cleanupPayload
    payload = reduce(lambda x, y: x.replace(y[0], y[1]), _, payload)
  File "lib/core/agent.py", line 281, in <lambda>
    payload = reduce(lambda x, y: x.replace(y[0], y[1]), _, payload)
AttributeError: 'tuple' object has no attribute 'replace'

**Comment by stamparm** [comment]
Bug introduced with 1ecb921ba766da32d8994266d7904e5590e77155
