### ISSUE TITLE
Unhandled exception (#9e9efb30)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#4922]
```
Running version: 1.5.12.6#dev
Python version: 3.10.1
Operating system: Windows-10-10.0.19042-SP0
Command line: sqlmap.py
Technique: None
Back-end DBMS: None
```
```
Traceback (most recent call last):
  File "lib/controller/controller.py", line 683, in start
    raise SqlmapNotVulnerableException(errMsg.rstrip('.'))
lib.core.exception.SqlmapNotVulnerableException: all tested parameters do not appear to be injectable. Try to increase values for '--level'/'--risk' options if you wish to perform more tests. If you suspect that there is some kind of protection mechanism involved (e.g. WAF) maybe you could try to use option '--tamper' (e.g. '--tamper=space2comment') and/or switch '--random-agent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 214, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 740, in start
    logger.error(errMsg.lstrip(", "))
TypeError: Logger.error() missing 2 required positional arguments: 'args' and 'kwargs'
```

**Comment by stamparm** [comment]
Fake news. sqlmap is proven to work with Windows/Python3.10, while `logger.error` is a standard Python's function call. Somebody messed something AFAICS
