### ISSUE TITLE
module 'MySQLdb' has no attribute 'Warning'

### ISSUE THREAD

**Issue by yarkable** [sqlmapproject/sqlmap#4060]
**Describe the bug**
I just updated my sqlmap from 1.4.8#stable to 1.4.12-1, and it works well in 1.4.8#stable, however, it has this problem in the newest version. The target site is based on SQLite. 

**To Reproduce**
1. Run:  sqlmap -u "http://2018shell2.picoctf.com:28120/" --form --dump-all
2.
 ```
Traceback (most recent call last):
  File "/usr/bin/sqlmap", line 44, in <module>
    from lib.core.common import banner
  File "/usr/share/sqlmap/lib/core/common.py", line 184, in <module>
    from lib.utils.sqlalchemy import _sqlalchemy
  File "/usr/share/sqlmap/lib/utils/sqlalchemy.py", line 27, in <module>
    warnings.filterwarnings("error", category=MySQLdb.Warning)
AttributeError: module 'MySQLdb' has no attribute 'Warning'
```

**Expected behavior**

It will exploit the website automatically

**Screenshots**
![](https://i.loli.net/2020/01/03/eYVW8fDmPynv7HJ.png)

**Running environment:**
 - sqlmap version: 1.4.12-1
 - Installation method: apt-get install
 - Operating system: Kali Linux 3
 - Python version: 3.7

**Target details:**
 - DBMS: SQLite

**More details**

However, in the end, I comment one line in `/usr/share/sqlmap/lib/utils/sqlalchemy.py` to ignore the error

```
#warnings.filterwarnings("error", category=MySQLdb.Warning)
```

**Comment by stamparm** [comment]
Duplicate of #4050 (fixed 12 days ago)
