### ISSUE TITLE
Misplaced flags in re.sub() calls

### ISSUE THREAD

**Issue by jwilk** [sqlmapproject/sqlmap#2500]
This is follow-up to #2481.

`lib/core/option.py` contains two instances of `re.sub()` calls that have misplaced flags argument:
```python
    if conf.data:
        conf.data = re.sub(INJECT_HERE_MARK.replace(" ", r"[^A-Za-z]*"), CUSTOM_INJECTION_MARK_CHAR, conf.data, re.I)

    if conf.url:
        conf.url = re.sub(INJECT_HERE_MARK.replace(" ", r"[^A-Za-z]*"), CUSTOM_INJECTION_MARK_CHAR, conf.url, re.I)
```
The 4th argument of `re.sub()` is supposed to be the maximum number of substitutions, not flags.

Found using [pydiatra](https://github.com/jwilk/pydiatra).

**Comment by stamparm** [comment]
Thx

**Comment by jwilk** [comment]
15a1d55812fdf53f943a06275ab62be96ecfa33d doesn't work on Python 2.6 (which I believe you still support):
```
TypeError: sub() got an unexpected keyword argument 'flags'
```

**Comment by stamparm** [comment]
Done
